"""initial schema

Revision ID: 07e4d3956e63
Revises: c72516f0c5b2
Create Date: 2026-07-06 11:59:58.784348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07e4d3956e63'
down_revision: Union[str, Sequence[str], None] = 'c72516f0c5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=150), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)

    # --- MOVED UP: change users.id type BEFORE any FK references it ---
    op.add_column('users', sa.Column('endpoint_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'"))
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # --- END moved block ---

    op.add_column('sms', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('sms', sa.Column('received_at', sa.Integer(), nullable=False))
    op.add_column('sms', sa.Column('read', sa.Boolean(), nullable=False))
    op.alter_column('sms', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('sms', 'sender',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('sms', 'message',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('sms', 'device_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('sms', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_sms_id'), table_name='sms')
    op.create_index('idx_sms_device', 'sms', ['device_id'], unique=False)
    op.create_index('idx_sms_sender', 'sms', ['sender'], unique=False)
    op.create_index('idx_sms_user_timestamp', 'sms', ['user_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_sms_device_id'), 'sms', ['device_id'], unique=False)
    op.create_index(op.f('ix_sms_sender'), 'sms', ['sender'], unique=False)
    op.create_index(op.f('ix_sms_timestamp'), 'sms', ['timestamp'], unique=False)
    op.create_index(op.f('ix_sms_user_id'), 'sms', ['user_id'], unique=False)
    op.create_foreign_key(None, 'sms', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'sms', 'devices', ['device_id'], ['device_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'user'"))
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'endpoint_url')
    op.drop_constraint(None, 'sms', type_='foreignkey')
    op.drop_constraint(None, 'sms', type_='foreignkey')
    op.drop_index(op.f('ix_sms_user_id'), table_name='sms')
    op.drop_index(op.f('ix_sms_timestamp'), table_name='sms')
    op.drop_index(op.f('ix_sms_sender'), table_name='sms')
    op.drop_index(op.f('ix_sms_device_id'), table_name='sms')
    op.drop_index('idx_sms_user_timestamp', table_name='sms')
    op.drop_index('idx_sms_sender', table_name='sms')
    op.drop_index('idx_sms_device', table_name='sms')
    op.create_index(op.f('ix_sms_id'), 'sms', ['id'], unique=False)
    op.alter_column('sms', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('sms', 'device_id',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('sms', 'message',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('sms', 'sender',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('sms', 'id',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('sms', 'read')
    op.drop_column('sms', 'received_at')
    op.drop_column('sms', 'user_id')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
