"""create settings and sms_cache tables

Revision ID: 3e4dffe6eee8
Revises: 21b5d749ebab
Create Date: 2026-08-12 13:46:02.294841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4dffe6eee8'
down_revision: Union[str, Sequence[str], None] = '21b5d749ebab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('settings_device_id_key'), 'settings', type_='unique')
    op.drop_index(op.f('ix_settings_device_id'), table_name='settings')
    op.create_index(op.f('ix_settings_device_id'), 'settings', ['device_id'], unique=True)
    op.drop_index(op.f('idx_sms_device_deleted_timestamp'), table_name='sms_cache')
    op.create_index('idx_sms_device_deleted_timestamp', 'sms_cache', ['device_id', 'deleted', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sms_device_deleted_timestamp', table_name='sms_cache')
    op.create_index(op.f('idx_sms_device_deleted_timestamp'), 'sms_cache', ['device_id', 'deleted', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index(op.f('ix_settings_device_id'), table_name='settings')
    op.create_index(op.f('ix_settings_device_id'), 'settings', ['device_id'], unique=False)
    op.create_unique_constraint(op.f('settings_device_id_key'), 'settings', ['device_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
