"""add user endpoint settings

Revision ID: b51e00bffc73
Revises: bddcc339af23
Create Date: 2026-07-07 14:01:48.296210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b51e00bffc73'
down_revision: Union[str, Sequence[str], None] = 'bddcc339af23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('storage_endpoint', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('storage_api_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('dashboard_endpoint', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('dashboard_api_key', sa.String(length=500), nullable=True))
    op.drop_column('users', 'endpoint_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('endpoint_url', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('users', 'dashboard_api_key')
    op.drop_column('users', 'dashboard_endpoint')
    op.drop_column('users', 'storage_api_key')
    op.drop_column('users', 'storage_endpoint')
    # ### end Alembic commands ###
