from typing import Optional
from datetime import datetime
from pydantic import BaseModel, Field


class Sms(BaseModel):
    """
    SMS received from the Android application.
    """

    # Unique ID generated by the phone
    id: str = Field(..., min_length=1)

    sender: str
    message: str
    device_id: str

    # Epoch milliseconds when phone received SMS
    received_at: int

    role: Optional[str] = "user"

    read: bool = False

    # Optional server timestamp
    timestamp: Optional[datetime] = None


class User(BaseModel):
    username: str
    email: str
    password: str
    role: Optional[str] = None

    # Optional per-user forwarding endpoint
    endpoint_url: Optional[str] = None


class LoginRequest(BaseModel):
    username: str
    password: str


class HealthResponse(BaseModel):
    status: str
    service: str
    version: str